name: helloGithubAction

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # 개인 토큰을 사용할 것인지 말 것인지
        persist-credentials: false 
    - name: 1. pip 업그래이드
      run: python -m pip install --upgrade pip
    - name: 2. 환경 설정
      run: pip install -r requirements.txt
    - name: 3. 셀레니움 설정
      run: pip install selenium
    - name: 4. 환경 설정
      run: pip install chromedriver
    - name: 5.우분투 설정
      run: |        
        sudo apt-get install fonts-unfonts-core
        sudo apt-get install fonts-unfonts-extra
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add        
        sudo apt-get install google-chrome-stable    
        wget https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip
        unzip ./chromedriver_linux64.zip
        
    - name: 6. 파이썬 실행
      run: python test.py
    - name: Commit files
      run: |
        git config --local user.email "paullabkorea@gmail.com"
        git config --local user.name "paullabkorea"
        git add .
        git commit -m "Run crawler and update current data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}   
